### ISSUE TITLE
Is there a way to test my CIFS mounts before setting up the script?

### ISSUE THREAD

**Issue by petercockroach** [marcone/teslausb#112]
I'm hitting this:
```
Mon Jul  1 23:57:13 PDT 2019 : verify-archive-configuration: Installing/updating required packages if needed
Mon Jul  1 23:57:18 PDT 2019 : verify-archive-configuration: Done
Mon Jul  1 23:57:18 PDT 2019 : verify-archive-configuration: Verifying that the archive server K2 is reachable...
Mon Jul  1 23:57:18 PDT 2019 : verify-archive-configuration: STOP: The archive server K2 is unreachable. Try specifying its IP address instead.
```
I'm trying to connect to a Mac which has a shared folder set up but it's clearly not working. What's the best way to test that I can reach this mount using cifs?

**Comment by marcone** [comment]
Note that on Mac OS you explicitly need to select that it's a CIFS/SMB share instead of an Apple share.
That being said, I was never successful in accessing a Mac shared folder from the Pi.

To test manually, just use the `mount` command directly from the command line. See `man mount` and `man mount.cifs`.
