### ISSUE TITLE
Excessive DNS requests

### ISSUE THREAD

**Issue by waltersobchak40** [marcone/teslausb#192]
I have my TeslaUSB stick configured to upload files Rsync. I have noticed that when the car is awake the device is making over 100 DNS requests per minute only to the server it is uploading to. This isn’t a huge issue, but seems like an area to be optimized.

**Comment by marcone** [comment]
Not sure how to optimize that given that teslausb is just a bunch of bash scripts that don't do any dns lookups themselves. You could try if installing something like nscd or dnsmasq fixes the problem, but otherwise you'll have to take it up with the the maintainers of the tool that causes the dns lookups.
