### ISSUE TITLE
Beginner needs help

### ISSUE THREAD

**Issue by scott7911** [marcone/teslausb#196]
I have a question about file transfers to my desktop. 

The RPI transfers files to my desktop when connected to my network but it doesn't transfer all files and the files it transfers have no distinction if they are "saved clips" or "Sentry clips" or "recent" recordings. It doesn't create "saved" and "recents" folders on my desktop. Also the the dates and times on the transfered files are incorrect, but they're correct on the files on the RPI. 
All of the files on the RPI are in the "recents" folder and the "saved" folder is empty, even if I have manually saved files using the touchscreen. 

Is it working properly?

Thanks

[diagnostics.txt](https://github.com/marcone/teslausb/files/3553054/diagnostics.txt)

**Comment by marcone** [comment]
Looks like it's working properly. Teslausb only archives files under the 'SavedClips' folder on the 'CAM' drive, and deletes them from the CAM drive afterwards, which is why the SavedClips folder will be empty after a successful archive run.
The car makes no distinction between Sentry and manually saved files.
