### ISSUE TITLE
"get_script failed, retrying"

### ISSUE THREAD

**Issue by rohan3au** [marcone/teslausb#200]
Stuck at this point, i SSH'd into the device, and it's looking for the setup variables file, which is no longer there and appears to be being deleted along the way.

I've taken the SD card out, put it into my computer and the file is gone, so I reload it onto the raspberry pi and start the process over again, and it happens again and the file disappears...

It appears the config gets moved to /root and then can't be found?

I have no idea where to go from here.

<img width="819" alt="Screen Shot 2019-08-29 at 7 05 45 pm" src="https://user-images.githubusercontent.com/54657749/63927016-3bddbe00-ca90-11e9-8c1e-cbdf2795cc5d.png">

**Comment by marcone** [comment]
This is normal. The .conf file is moved from /boot to /root by the setup process, and the setup scripts will find it in either location.
The fact that get_script is failing for so long likely means your the Pi is not actually connected to wifi, probably because you specified the wrong wifi credentials.
