### ISSUE TITLE
Cloning Repository

### ISSUE THREAD

**Issue by DonC52** [marcone/teslausb#225]
You noted to get the current repository, I can either press download (to get a .zip) file or Import into my own repository.   Is that where I use the https://github.com/marcone/teslausb.git link I get when selecting clone? Do I enter that address when I select Import Repository?  Does that keep the additions you and the contributors make synced with my repository? 

Or is it better to just use the download .zip file or do I simply use the fork button.

**Comment by marcone** [comment]
The fork button will make a fork of this project under your own github account. It will be a new project, downstream of this one. Changes in the upstream (this) project won't automatically propagate to the new project.

"git clone https://github.com/marcone/teslausb.git" syncs down *this* project to your local machine. You can trivially pull in new changes by running "git pull".

The zipfile just contains the sources, no git project info.

You probably want option number 1 (fork), since the setup scripts download the latest versions of the scripts directly from github, and you can just set the REPO variable in the .conf to point at your own fork.
