### ISSUE TITLE
guidance

### ISSUE THREAD

**Issue by marckatznelson** [marcone/teslausb#407]
Hi - I wanted to know how the sentry and dashcam video automatic delete takes place. Yesterday, my dashcam notified that there is no space in the usb, hence cannot record. When I looked at the directories, I saw TeslaCam folder had 3 days of recording, which is the reason new dashcam videos did not record.
1. How does the auto delete of all videos from USB work?
2. If I copy over and delete videos using linux commands (manually) on the pi, what directories should I completely delete to create space. I tried deleting all folders under TeslaCam (in the backingfiles dir) already. I did not delete the 'Snapshots' directory though. Should I delete that too? I tried but that has read-only mp4's.

thanks
marc

**Comment by marcone** [comment]
If the car tells you that the disk is full, it's talking about the disk image at /backingfiles/cam_disk.bin.
Deleting files in e.g. /backingfiles/TeslaCam won't help, because that doesn't free up space inside the disk image that the car sees.
You can check if the disk image is full by plugging the Pi in to a PC.
Recordings are normally deleted from the disk image after they are archived.
