### ISSUE TITLE
Rclone config file issue

### ISSUE THREAD

**Issue by murtuzahabib** [marcone/teslausb#574]
After successfully setting up rclone, getting the error when trying to ls into mapped google drive.

"Failed to save config after 10 tries: Failed to create temp file for new config: open /root/.config/rclone/rclone.conf705945223: read-only file system"

24 hours ago, could ls into the mapped drive and see the files in it.

**Comment by marcone** [comment]
Did you change the archive method to "rclone" in the config file and run setup again?

**Comment by murtuzahabib** [comment]
Yes, did as per instructions. I could access the files in the gdrive from terminal. 

When i try doing that 24 hours later, i get the above error.

**Comment by marcone** [comment]
Check that /root/.config/rclone is a link to /mutable/configs/rclone

**Comment by murtuzahabib** [comment]
using <ls -l /mutable/configs/rclone/>, it gives me: "ls: cannot access '/mutable/configs/rclone/': No such file or directory"

**Comment by marcone** [comment]
And what about `ls -la /root/.config/` ?

**Comment by murtuzahabib** [comment]
As per my very limited linux/coding understanding:

root@teslausb:~# ls -la /root/.config/
total 12
drwxr-xr-x 3 root root 4096 Dec 13 23:36 .
drwx------ 6 root root 4096 Dec 14 00:03 ..
drwxr-xr-x 2 root root 4096 Dec 13 23:41 rclone

**Comment by marcone** [comment]
OK, so that's an actual folder on the root partition, which explains the "read-only file system" error you are seeing.
/root/.config/rclone is supposed to be a symbolic link to /mutable/configs/rclone
The setup script achieves this by moving /root/.config/rclone to /mutable/configs/rclone and then creating the link.
The fact that it is not a link would therefore seem to indicate that that setup script didn't run. You said it worked before, though, so I think that previously the root partition wasn't read-only, e.g. because you had made it writeable in order to configure rclone, and didn't re-run setup and reboot afterwards.

You should be able to get things working again by ensuring that the required variables are specified in the config file, and then running setup again. See the "Easy rclone setup" section in https://github.com/marcone/teslausb/blob/main-dev/doc/SetupRClone.md

**Comment by murtuzahabib** [comment]
Re-run the rclone setup, variables supplied. Working now. Hopefully stays working.

Thanks again.

**Comment by murtuzahabib** [comment]
Hi, would the application archive to google drive automatically whilst connected to the wifi (if so, then I don't see any files transferred)  or, does one need to run a certain rclone command to do that?

If the latter, could you please share the rclone command format? 

Thanks.

**Comment by marcone** [comment]
If you configured rclone and teslausb correctly it will archive automatically.
