### ISSUE TITLE
Can't change password / drives don't show

### ISSUE THREAD

**Issue by Jodox1976** [marcone/teslausb#631]
[diagnostics.txt](https://github.com/marcone/teslausb/files/6368483/diagnostics.txt)
When I try changing the password using the passwd command, type the current password raspberry, then type the new one two times, I get "Authentication token manipulation error".

And shouldn't the CAM and MUSIC drives show up, when I connect teslausb via usb to my PC?

**Comment by marcone** [comment]
> [diagnostics.txt](https://github.com/marcone/teslausb/files/6368483/diagnostics.txt)
> When I try changing the password using the passwd command, type the current password raspberry, then type the new one two times, I get "Authentication token manipulation error".

That's because the root filesystem is read-only. You need to remount it read/write to make changes: https://github.com/marcone/teslausb#optional-making-changes-to-the-system-after-setup
 
> And shouldn't the CAM and MUSIC drives show up, when I connect teslausb via usb to my PC?

According to your diagnostics it was still copying music from your server. Once that is done the drives should show up on your computer.
