### ISSUE TITLE
TeslaUSB notifies about archiving files that are not really new (and not really archived)

### ISSUE THREAD

**Issue by joanquro** [marcone/teslausb#636]
Hello.

I'm using no-snapshot branch since yesterday.

Every time I wake up my Model 3, TeslaUSB notifies me in Telegram about some events to archive, but it really does not archive anything (expected 
[diagnostics.txt](https://github.com/marcone/teslausb/files/6440170/diagnostics.txt)
[archiveloop.log](https://github.com/marcone/teslausb/files/6440172/archiveloop.log)

because there are not new videos). Why is this happening?. See screen capture.

![image](https://user-images.githubusercontent.com/62767148/117421354-c1c93200-af1e-11eb-9c8c-d87e202395a5.png)

I attach diagnostics.txt and archiveloop.log

I wonder if there's a way to begin "from scratch", e.g., erasing all files in TeslaCam folder without having to reflash and setup again everything. Is this possible?.

Thanks.

**Comment by marcone** [comment]
I suspect this is because you first installed from the main-dev branch, and then switched to the no-snapshots branch. The easiest way to fix this is to delete all the recordings (either from the car's Sentry viewer, or by plugging the Pi in to a computer, waiting for the CAM drive to show up, then deleting all the recordings).
