### ISSUE TITLE
Refresh models - pi triggering car alarm?

### ISSUE THREAD

**Issue by miles267** [marcone/teslausb#690]
Previously had a 2019 M3 with Pi0 without any issues.  Recently acquired a 2021 refresh M3 where I'm using same Pi0 in glovebacks USB3 port.  While it works reliably despite the usual 'no usb connected in glovebox' messages, I've encountered numerous cases where the car wakes from sleep to trigger a sync from Pi0 and triggers the car alarm.

I am switching between my operable Pi0/teslausb device from former 2019 car and the Tesla factory USB3 drive.  Certainly not implying this is a teslausb issue, but wondered whether anyone else has observed similar behavior?  It doesn't seem to occur when the Tesla factor USB3 thumb drive is inserted into the glovebox USB port.  

Have read other posts (elsewhere) about situations where the alarm was triggered when car failed to find/mount the usb properly as a measure to alarm driver that someone might've been theft of the usb storage drive.  Not sure whether that is anecdotal or proven.

**Comment by marcone** [comment]
Sounds similar to https://github.com/marcone/teslausb/issues/68

**Comment by miles267** [comment]
Interesting.  Thank you @marcone for linking me to it.  Incidentally my car is a new "Vision" car on what the service tech referred to as an "islanded" firmware: 2021.11.103.  A new vehicle build that remains for several weeks before eligible for any updates.  Am unable to even find it in any of the firmware version trackers.  It's lacking many of the newer features, but indicates it's a v10 build.  Not sure whether any other users are on any build this new.

What is also peculiar, when this behavior occurs (last night it happened at 1:53 AM; unexpectedly, car alarm blasting in garage), the drivers door opens and it reports a "manual door release" used error.  Had the entire door lock+latch assembly replaced to ensure that's not the case.

**Comment by CodeChief** [comment]
Log a service request with Tesla. They do remote diagnostics now (something new it seems as they sent me a survey about how good it was afterwards). I had random car alarms any time of day about the same time as a firmware update and TeslaUsb update so after watching the car like a hawk and seeing nothing I too suspected it had to be the only thing I knew which had problems, TeslaUsb. But, In the end it was an insect in the car and they could tell me exactly which seat it was on (amazing) the next day a dead insect was lying there on the passenger seat.

It happened again later and what do you know another one but this time I didn't bother to log a call of course. We had an unusual summer which caused an extreme amount of insects I had to deal with later. They love all the places to hide along the gaps between the glass panels.

Just go back to the original refresh (Samsung USB3) USB stick for a week and wait to see if the alarm goes off again. But you could actually log a call to get accurate information. They didn't charge me anything for it.

**Comment by miles267** [comment]
@codechief how do you initiate a remote diagnostic request from the Tesla mobile app?  I had a mobile service tech on site yesterday.  They replaced the entire driver door lock assembly including electric door switch, manual door release, latch, etc and it didn't remedy the issue.  If I try to call the Tesla contact #, it redirects back to the app.  Exhausting.  This still seems a mechanical issue to me.

**Comment by calvarez** [comment]
You create a service request, and they will automatically do the diagnostic.  I had an AP problem and they did that.

I've had one false alarm since I got the car in April.  (2019 M3 LR)

**Comment by CodeChief** [comment]
> @CodeChief how do you initiate a remote diagnostic request from the Tesla mobile app? I had a mobile service tech on site yesterday. They replaced the entire driver door lock assembly including electric door switch, manual door release, latch, etc and it didn't remedy the issue. If I try to call the Tesla contact #, it redirects back to the app. Exhausting. This still seems a mechanical issue to me.

Yes it's a normal service request in the app which should be redirected to a mobile service instead of a visit to a service center. I didn't know anything about remote diagnostics, I just received an SMS from the mobile guy and once confirmed the service request was cancelled (successful).

![IMG_20211016_172029](https://user-images.githubusercontent.com/1496225/137592924-74f4e9c1-47b4-40e3-9fc9-72e894183d94.jpg)
![IMG_20211016_171524](https://user-images.githubusercontent.com/1496225/137592935-9d0e3457-d4a6-4d2d-a19d-dbf3ac92acef.jpg)
![IMG_20211016_171409](https://user-images.githubusercontent.com/1496225/137592947-1fd3a5a9-5b68-413c-8407-aa6206f1a7f3.jpg)

This was in Germany though. Not sure if "Ferndiagnostik" is available in all regions. It makes sense. Perhaps you need to ensure you have a good WiFi/LTE connection whilst parked. Maybe they check if the car is accessible first when starting to plan the visit. As mentioned in the SMS they are interested in a specific timestamp in case it's not solved so maybe start noting the exact times it goes off in preparation. Good luck!
