### ISSUE TITLE
Not a issue but question about file formatting

### ISSUE THREAD

**Issue by jamesp132** [marcone/teslausb#698]
Hello! 

Is there a way to get savedclips and sentryclips to organise like recentclips where it stored the files by day and then the video clips from that day?

Rather than how it is currently by just putting all the files straight into the directory folder? 

Many thanks

James

**Comment by marcone** [comment]
> Rather than how it is currently by just putting all the files straight into the directory folder?

Saved and Sentry events are already grouped in folders (one folder per event). It's certainly technically possible to further group those by day, but this is not currently implemented. Happy to accept a PR.

(RecentClips are grouped by day because otherwise all of those recordings, potentially going back weeks or months, would be in the same folder)
